### PR TITLE
fix(wren-ui): fix auto-generated relationships

### LINKED ISSUE #193: failed to deploy model if I apply the auto-generated table relationships
**Describe the bug**
I used the [instructions here to dump pagila database to my local postgresql db](https://neon.tech/docs/import/import-sample-data#pagila-database). If I skip the relationship connection step, the model is deployed successfully; however, the model is failed to deploy if I apply the auto-generated table relationships

error message:
```json
{
    "errors": [
        {
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "saveRelations"
            ],
            "message": "insert into `relation` (`from_column_id`, `join_type`, `name`, `project_id`, `to_column_id`) select 184 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.addressPublic.city' as `name`, 4 as `project_id`, 191 as `to_column_id` union all select 193 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.cityPublic.country' as `name`, 4 as `project_id`, 195 as `to_column_id` union all select 203 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.customerPublic.address' as `name`, 4 as `project_id`, 180 as `to_column_id` union all select 199 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.customerPublic.store' as `name`, 4 as `project_id`, 339 as `to_column_id` union all select 221 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.filmPublic.language' as `name`, 4 as `project_id`, 249 as `to_column_id` union all select 222 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.filmPublic.language' as `name`, 4 as `project_id`, 249 as `to_column_id` union all select 231 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.film_actorPublic.actor' as `name`, 4 as `project_id`, 172 as `to_column_id` union all select 232 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.film_actorPublic.film' as `name`, 4 as `project_id`, 217 as `to_column_id` union all select 235 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.film_categoryPublic.category' as `name`, 4 as `project_id`, 188 as `to_column_id` union all select 234 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.film_categoryPublic.film' as `name`, 4 as `project_id`, 217 as `to_column_id` union all select 246 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.inventoryPublic.film' as `name`, 4 as `project_id`, 217 as `to_column_id` union all select 247 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.inventoryPublic.store' as `name`, 4 as `project_id`, 339 as `to_column_id` union all select 267 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_01Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 269 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_01Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 268 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_01Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 273 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_02Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 275 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_02Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 274 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_02Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 279 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_03Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 281 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_03Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 280 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_03Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 285 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_04Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 287 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_04Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 286 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_04Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 291 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_05Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 293 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_05Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 292 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_05Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 297 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_06Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 299 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_06Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 298 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_06Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 311 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.rentalPublic.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 310 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.rentalPublic.inventory' as `name`, 4 as `project_id`, 245 as `to_column_id` union all select 313 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.rentalPublic.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 323 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.staffPublic.address' as `name`, 4 as `project_id`, 180 as `to_column_id` union all select 325 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.staffPublic.store' as `name`, 4 as `project_id`, 339 as `to_column_id` union all select 341 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.storePublic.address' as `name`, 4 as `project_id`, 180 as `to_column_id` returning * - UNIQUE constraint failed: relation.name",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "message": "insert into `relation` (`from_column_id`, `join_type`, `name`, `project_id`, `to_column_id`) select 184 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.addressPublic.city' as `name`, 4 as `project_id`, 191 as `to_column_id` union all select 193 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.cityPublic.country' as `name`, 4 as `project_id`, 195 as `to_column_id` union all select 203 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.customerPublic.address' as `name`, 4 as `project_id`, 180 as `to_column_id` union all select 199 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.customerPublic.store' as `name`, 4 as `project_id`, 339 as `to_column_id` union all select 221 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.filmPublic.language' as `name`, 4 as `project_id`, 249 as `to_column_id` union all select 222 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.filmPublic.language' as `name`, 4 as `project_id`, 249 as `to_column_id` union all select 231 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.film_actorPublic.actor' as `name`, 4 as `project_id`, 172 as `to_column_id` union all select 232 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.film_actorPublic.film' as `name`, 4 as `project_id`, 217 as `to_column_id` union all select 235 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.film_categoryPublic.category' as `name`, 4 as `project_id`, 188 as `to_column_id` union all select 234 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.film_categoryPublic.film' as `name`, 4 as `project_id`, 217 as `to_column_id` union all select 246 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.inventoryPublic.film' as `name`, 4 as `project_id`, 217 as `to_column_id` union all select 247 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.inventoryPublic.store' as `name`, 4 as `project_id`, 339 as `to_column_id` union all select 267 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_01Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 269 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_01Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 268 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_01Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 273 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_02Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 275 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_02Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 274 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_02Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 279 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_03Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 281 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_03Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 280 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_03Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 285 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_04Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 287 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_04Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 286 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_04Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 291 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_05Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 293 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_05Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 292 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_05Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 297 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_06Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 299 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_06Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 298 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_06Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 311 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.rentalPublic.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 310 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.rentalPublic.inventory' as `name`, 4 as `project_id`, 245 as `to_column_id` union all select 313 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.rentalPublic.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 323 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.staffPublic.address' as `name`, 4 as `project_id`, 180 as `to_column_id` union all select 325 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.staffPublic.store' as `name`, 4 as `project_id`, 339 as `to_column_id` union all select 341 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.storePublic.address' as `name`, 4 as `project_id`, 180 as `to_column_id` returning * - UNIQUE constraint failed: relation.name",
                "shortMessage": "Internal server error",
                "stacktrace": [
                    "SqliteError: insert into `relation` (`from_column_id`, `join_type`, `name`, `project_id`, `to_column_id`) select 184 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.addressPublic.city' as `name`, 4 as `project_id`, 191 as `to_column_id` union all select 193 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.cityPublic.country' as `name`, 4 as `project_id`, 195 as `to_column_id` union all select 203 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.customerPublic.address' as `name`, 4 as `project_id`, 180 as `to_column_id` union all select 199 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.customerPublic.store' as `name`, 4 as `project_id`, 339 as `to_column_id` union all select 221 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.filmPublic.language' as `name`, 4 as `project_id`, 249 as `to_column_id` union all select 222 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.filmPublic.language' as `name`, 4 as `project_id`, 249 as `to_column_id` union all select 231 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.film_actorPublic.actor' as `name`, 4 as `project_id`, 172 as `to_column_id` union all select 232 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.film_actorPublic.film' as `name`, 4 as `project_id`, 217 as `to_column_id` union all select 235 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.film_categoryPublic.category' as `name`, 4 as `project_id`, 188 as `to_column_id` union all select 234 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.film_categoryPublic.film' as `name`, 4 as `project_id`, 217 as `to_column_id` union all select 246 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.inventoryPublic.film' as `name`, 4 as `project_id`, 217 as `to_column_id` union all select 247 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.inventoryPublic.store' as `name`, 4 as `project_id`, 339 as `to_column_id` union all select 267 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_01Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 269 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_01Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 268 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_01Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 273 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_02Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 275 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_02Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 274 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_02Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 279 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_03Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 281 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_03Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 280 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_03Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 285 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_04Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 287 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_04Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 286 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_04Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 291 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_05Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 293 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_05Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 292 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_05Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 297 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_06Public.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 299 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_06Public.rental' as `name`, 4 as `project_id`, 308 as `to_column_id` union all select 298 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.payment_p2022_06Public.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 311 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.rentalPublic.customer' as `name`, 4 as `project_id`, 198 as `to_column_id` union all select 310 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.rentalPublic.inventory' as `name`, 4 as `project_id`, 245 as `to_column_id` union all select 313 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.rentalPublic.staff' as `name`, 4 as `project_id`, 320 as `to_column_id` union all select 323 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.staffPublic.address' as `name`, 4 as `project_id`, 180 as `to_column_id` union all select 325 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.staffPublic.store' as `name`, 4 as `project_id`, 339 as `to_column_id` union all select 341 as `from_column_id`, 'ONE_TO_MANY' as `join_type`, 'Public.storePublic.address' as `name`, 4 as `project_id`, 180 as `to_column_id` returning * - UNIQUE constraint failed: relation.name",
                    "    at Client_BetterSQLite3._query (/Users/cyyeh/Desktop/canner/repos/WrenAI/wren-ui/node_modules/knex/lib/dialects/better-sqlite3/index.js:39:40)",
                    "    at executeQuery (/Users/cyyeh/Desktop/canner/repos/WrenAI/wren-ui/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)",
                    "    at Client_BetterSQLite3.query (/Users/cyyeh/Desktop/canner/repos/WrenAI/wren-ui/node_modules/knex/lib/client.js:154:12)",
                    "    at Runner.query (/Users/cyyeh/Desktop/canner/repos/WrenAI/wren-ui/node_modules/knex/lib/execution/runner.js:141:36)",
                    "    at ensureConnectionCallback (/Users/cyyeh/Desktop/canner/repos/WrenAI/wren-ui/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)",
                    "    at Runner.ensureConnection (/Users/cyyeh/Desktop/canner/repos/WrenAI/wren-ui/node_modules/knex/lib/execution/runner.js:318:20)",
                    "    at runMicrotasks (<anonymous>)",
                    "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
                    "    at async Runner.run (/Users/cyyeh/Desktop/canner/repos/WrenAI/wren-ui/node_modules/knex/lib/execution/runner.js:30:19)",
                    "    at async RelationRepository.createMany (webpack-internal:///(api)/./src/apollo/server/repositories/baseRepository.ts:87:24)",
                    "    at async ModelService.saveRelations (webpack-internal:///(api)/./src/apollo/server/services/modelService.ts:200:32)",
                    "    at async ProjectResolver.saveRelations (webpack-internal:///(api)/./src/apollo/server/resolvers/projectResolver.ts:229:32)"
                ]
            }
        }
    ],
    "data": null
}
```

**Expected behavior**
I can successfully deploy the model if I apply the auto-generated table relationships

**Desktop (please complete the following information):**
 - OS: MacOS 14.4.1 (23E224)
 - PostgreSQL: 16
 - Browser: Brave

**WrenAI Information**
- Version: 0.2.1

### PR DESCRIPTION
**Pull request by fredalai**
## Description
 fix auto-generated relationships

## Solution
 - Will not see the duplicate rowKey error message in the console.log
 - Successfully apply auto-generated table relationships

## UI Screenshot

截圖 2024-05-16 下午3 38 32

## Issue ticket number
closes #193

### CODE REVIEW

File: wren-ui/src/apollo/server/services/modelService.ts [hunk 1]
```diff
@@ -498,11 +498,14 @@ export class ModelService implements IModelService {
...
     }
+
     return (
       fromModel.sourceTableName.charAt(0).toUpperCase() +
       fromModel.sourceTableName.slice(1) +
+      relation.fromColumnId +
       toModel.sourceTableName.charAt(0).toUpperCase() +
-      toModel.sourceTableName.slice(1)
+      toModel.sourceTableName.slice(1) +
+      relation.toColumnId
```
Comment (wwwy3y3) [inline wren-ui/src/apollo/server/services/modelService.ts:508]: Do you think maybe we can use column name instead of column id, so the relationship name at least makes more sense ?

Comment (fredalai) [reply wren-ui/src/apollo/server/services/modelService.ts]: sure~

File: wren-ui/src/apollo/server/services/modelService.ts [hunk 2]
```diff
@@ -492,17 +492,33 @@ export class ModelService implements IModelService {
...
       fromModel.sourceTableName.charAt(0).toUpperCase() +
       fromModel.sourceTableName.slice(1) +
+      fromColumn.referenceName.charAt(0).toUpperCase() +
+      fromColumn.referenceName.slice(1) +
       toModel.sourceTableName.charAt(0).toUpperCase() +
-      toModel.sourceTableName.slice(1)
+      toModel.sourceTableName.slice(1) +
+      toColumn.referenceName.charAt(0).toUpperCase() +
+      toColumn.referenceName.slice(1)
     );
```
Comment (wwwy3y3) [inline wren-ui/src/apollo/server/services/modelService.ts:522]: try using `capitalize` (https://lodash.com/docs/4.17.15#capitalize) ?
